require("config.init")
require("config.setup")
require("config.user")
require("config.appearance")
require("config.keys")
require("config.rules")
require("config.signals")
require("config.autostart")
